// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcq95V--RLDmLLyvmTzKbnaKdtVv4LNOc',
    appId: '1:297416734396:web:48a253b90b51de2636c2b9',
    messagingSenderId: '297416734396',
    projectId: 'belajaruts-a2021',
    authDomain: 'belajaruts-a2021.firebaseapp.com',
    databaseURL: 'https://belajaruts-a2021-default-rtdb.firebaseio.com',
    storageBucket: 'belajaruts-a2021.firebasestorage.app',
    measurementId: 'G-Y7774Q7GRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyihAlDslEqIm0A9Ie1nNgVR_5FFyIkpE',
    appId: '1:297416734396:android:f2161b5de30633b836c2b9',
    messagingSenderId: '297416734396',
    projectId: 'belajaruts-a2021',
    databaseURL: 'https://belajaruts-a2021-default-rtdb.firebaseio.com',
    storageBucket: 'belajaruts-a2021.firebasestorage.app',
  );
}
