// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwSTYZq_8YF-fdGKwZ2R4WqAXIlcJIHp8',
    appId: '1:175954555689:web:e9fd9482ef9417ed223d38',
    messagingSenderId: '175954555689',
    projectId: 'frist-app-b39ce',
    authDomain: 'frist-app-b39ce.firebaseapp.com',
    databaseURL: 'https://frist-app-b39ce-default-rtdb.firebaseio.com',
    storageBucket: 'frist-app-b39ce.firebasestorage.app',
    measurementId: 'G-XTVJX2E86G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxgH2kdfJ-S9EI6_8Z-lXVy1EcUUp4-4',
    appId: '1:175954555689:android:4634546c09e8be7b223d38',
    messagingSenderId: '175954555689',
    projectId: 'frist-app-b39ce',
    databaseURL: 'https://frist-app-b39ce-default-rtdb.firebaseio.com',
    storageBucket: 'frist-app-b39ce.firebasestorage.app',
  );
}
